packages:
  - "apps/*"
  - "packages/*"

catalog:
  tailwindcss: ^3.4.13
  typescript: ^5.6.3
  tsup: ^8.3.5
  postcss: ^8
  lucide-react: ^0.456.0
  autoprefixer: ^10
  zod: ^3.23.8
  framer-motion: ^11.15.0
  "@types/node": ^20
  ms: ^2.1.3

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
