import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        {/* @ts-expect-error Server Component */}
        <ClerkProvider>
          <nav>
            {/* @ts-expect-error Server Component */}
            <SignedOut>
              <SignInButton />
            </SignedOut>
            {/* @ts-expect-error Server Component */}
            <SignedIn>
              <UserButton />
            </SignedIn>
          </nav>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
